############# initial ##########
hostname: webscarper.local
folder: /var/www/webscarper
env: Development
packages: [
  git-core,
  curl,
  wget,
  htop,
  python-psycopg2,
  libpq-dev,
  unzip,
  zip,
  expect-dev,
  mc,
  acl
]
################################

########## nginx ###############
nginx_php_version: "7.0"
nginx_vhosts: [
    { server_name: 'api.webscarper.local', root: '{{ folder }}/api/web', template: 'yii'},
    { server_name: 'db.webscarper.local', root: '/usr/share/phppgadmin', template: 'php'}
]
################################

########## php-ubuntu ##########
php_ppa: "ppa:ondrej/php"
php_v: "{{ nginx_php_version }}"
php_packages: [
    "php{{ php_v }}-fpm",
    "php{{ php_v }}-dev",
    "php{{ php_v }}-cli",
    "php{{ php_v }}-pgsql",
    "php{{ php_v }}-mysql",
    "php{{ php_v }}-curl",
    "php{{ php_v }}-gd",
    "php{{ php_v }}-mcrypt",
    "php{{ php_v }}-mbstring",
    "php{{ php_v }}-intl",
    "php{{ php_v }}-xml",
]
php_max_execution_time: '60'
php_memory_limit: '128M'
php_error_reporting: 'E_ALL | E_STRICT'
php_display_errors: 'On' #Off
php_post_max_size: '35M'
php_file_uploads: 'On'
php_upload_max_filesize: '30M'
php_max_file_uploads: '20'
php_fpm_emergency_restart_threshold: '10'
php_fpm_emergency_restart_interval: '1m'
php_fpm_process_control_timeout: '30s'
php_fpm_log_level: 'error'
php_fpm_process_max: '0'
################################

########### pgsql ##############
pgdb_version: 9.5
pgdb_sudo_user: postgres
pgdb_sudo_pass: ''
pgdb_users: [
  {
    user: webscarper,
    password: sFwOPd89TP3,
    database: webscarper
  }
]
pgdb_databases: [
  webscarper
]
pgdb_postgresql_locale: en_US.UTF-8
pgdb_conf_src_file: configs/postgresql/postgresql.conf.j2
pgdb_max_connections: 200
pgdb_shared_buffers: 256MB
pgdb_effective_cache_size: 768MB
pgdb_work_mem: 1310kB
pgdb_maintenance_work_mem: 64MB
pgdb_min_wal_size: 1GB
pgdb_max_wal_size: 2GB
pgdb_checkpoint_completion_target: 0.7
pgdb_wal_buffers: 7864kB
pgdb_default_statistics_target: 100
pgdb_log_min_duration_statement: 1000
################################

############# composer #########
composer_global_require: "fxp/composer-asset-plugin:^1.3.1"
################################

############ cron ##############
crontab_file: configs/cron/dev/crontab.j2
################################